---
version: 2
workflows:
  version: 2
  test_all:
    jobs:
      - js
      - ts
      - swift

jobs:
  js:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: |
          cd ~/project/js/example
          npm install
          npm test
  ts:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: |
          cd ~/project/ts/example
          npm install
          npm test
  swift:
    docker:
      - image: kylef/swiftenv:1
    steps:
      - checkout
      - run: |
          cd ~/project/swift/example
          swiftenv install
          swift test
