---
version: 2.1

jobs:
  readme:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./tests
      - run:
          command: npm test
          working_directory: ./tests


  js:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./js/example
      - run:
          command: npm test
          working_directory: ./js/example

  ts:
    docker:
      - image: circleci/node:13.10.1
    steps:
      - checkout
      - run:
          command: npm install
          working_directory: ./ts/example
      - run:
          command: npm test
          working_directory: ./ts/example

  swift:
    docker:
      - image: swift:5.1.5
    steps:
      - checkout
      - run:
          command: swift test
          working_directory: ./swift/example

  cs:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          command: dotnet restore
          working_directory: ./cs/example
      - run:
          command: dotnet test
          working_directory: ./cs/example


workflows:
  test_all:
    jobs:
      - js
      - ts
      - swift
      - cs
